swc-windows-installer.py: Bump SQLite from 3.8.8.3 to 3.9.2
Released on 2015-11-02 [1].  For a summary of changes since 3.8.8.3
(released on 2015-02-25), see [1].  The old code was giving me:

  ValueError: downloaded
  'https://sqlite.org/2014/sqlite-shell-win32-x86-3080803.zip' has the
  wrong SHA-1 hash: 8a99a3ddd27097b072093319cd6e79bfbfa7480f !=
  a57f43b96827c549eb647a126779794e88022e46

Although the 2014 in the URL may have been a typo.

[1]: http://sqlite.org/news.html